<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOlXwQiY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOlXwQiY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOlXwQiY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOlXwQiY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOlXwQiY\App_KernelDevDebugContainer([
    'container.build_hash' => 'OlXwQiY',
    'container.build_id' => 'dfa1d606',
    'container.build_time' => 1666811500,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOlXwQiY');
